### ISSUE TITLE
Chapter numbers in Introduction are no longer correct

### ISSUE THREAD

**Issue by ARawles** [ARawles/teacheR#31]
Following the change to a "For Teachers" and "For Students" approach, the chapter numbers given in the introduction are no longer valid.

**Comment by Swapnil-2001** [comment]
@ARawles  I would like to work on this, but I am just starting out in open source contribution, could you suggest how to go about this?

**Comment by ARawles** [comment]
Sure.
The best way to contribute would be to fork this repository (https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks), make the changes in that forked version of the repository and then submit the changes as a pull request. I can then review the changes and accept them for the original branch.
